<?php 
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    $identity = $auth->getIdentity();
    $user_id = $identity['id'];
}
$db = Core_Db_Table::getDefaultAdapter();
$row = $db->fetchRow("SELECT * FROM user_exam WHERE user_id=" . $user_id . " ORDER BY exam_date DESC LIMIT 1");
$nganhNghes = $this->nganhNghes;
?>
<form method="POST" id="form1" onsubmit="return false;">
    <div class="row-fluid">
        <div class="span12">
            <div style="margin-top: 20px;" class="span3"<?php if (is_array($row) && count($row) > 0) echo ' onclick="viewResult();"'; ?>>
                <?php if (is_array($row) && count($row) > 0) { ?>
                    <button style="border-radius: 5px;background-color: brown;color: white;">
                        Xem kết quả lần thi gần nhất
                    </button>
                    <?php
                }
                ?>
                &nbsp;
            </div>

            <div class="span4" style="margin-top: 20px;">
                <select id="nganh_nghe_id" name="nganh_nghe_id" style="width: 100%;">
                    <option value="0">------------------Chọn ngành nghề------------------</option>
                    <?php foreach ($nganhNghes as $nganhNghe) { ?>
                        <option value="<?php echo $nganhNghe['id']; ?>"><?php echo $nganhNghe['title']; ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
            <div class="span3" style="margin-top: 20px;">
                <select id="level" name="level" style="width: 100%;">
                    <option value="0">-----------Chọn cấp bậc-----------</option>
                    <option value="<?php echo Default_Model_Question::SO_CAP; ?>">Sơ cấp</option>
                    <option value="<?php echo Default_Model_Question::TRUNG_CAP; ?>">Trung cấp</option>
                    <option value="<?php echo Default_Model_Question::CAO_CAP; ?>">Cao cấp</option>
                </select>
            </div>
            <!--<div class="span2" style="margin-top: 20px;"><input type="submit" value="Bắt đầu thi" id="start"/></div>-->
            <div class="span2" style="margin-top: 20px;" id="start">
                <a>Bắt đầu thi</a> 
            </div>
        </div>
    </div>

</form>

<script type="text/javascript">

    jQuery(function ($) {
        $("#start").click(function () {
            if ($("#nganh_nghe_id").val() == '0') {
                alert('Vui lòng chọn ngành nghề');
                $("#nganh_nghe_id").focus();
                return;
            }
            if ($("#level").val() == '0') {
                alert('Vui lòng chọn cấp bậc');
                $("#level").focus();
                return;
            }
            $("#form1").attr('onsubmit', 'return true');
            $("#form1").submit();
        });
        $("#nganh_nghe_id").val('<?php echo $this->nganhNgheId; ?>');
        $("#level").val('<?php echo $this->level; ?>');

    });


</script>
