<script type="text/javascript">
    function save() {
        document.form.submit();
    }
    function backItemIndex() {
        url = "<?php echo $this->baseUrl('/admin/nganhnghe/'); ?>";
        window.location = url;
    }

</script>
<?php
$message = $this->message;
if ($message != "") {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span3">&nbsp;</div>
        <div class="span6" align='center' style='color: red;'>
            <?php
            echo $message;
            ?>
        </div>
        <div class="span3">&nbsp;</div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='padding-bottom:20px;color: red;margin-bottom: 20px;'>
        <div class="textHeader" style="-moz-border-radius: 10px 10px 10px 10px;background-color:#f2e8e8;">	  
            <div onclick="save();" style="float: right;text-decoration: underline;color: blue;cursor: pointer;">Lưu</div>
            <div onclick="backItemIndex();" style="float: right;margin-right: 10px;text-decoration: underline;color: blue;cursor: pointer;">Đóng</div>
            <div style="clear: both;"></div>
        </div>

    </div>
    <div class="span3">&nbsp;</div>
</div>
<form name="form" enctype="multipart/form-data" id="form" action="<?php echo $this->url(); ?>" method="post">
    <div class="row-fluid" style="margin-top: 10px;">
        <div class="span4">&nbsp;</div>

        <div class="span12">
            <?php echo $this->form($this, $this->form, 1, $echo_form_tag = FALSE); ?>
        </div>

    </div>

    <div class="row-fluid" style="margin-top: 10px;">



        <?php
        if ($this->form->getElement('question_id') == null) {

            $rows = Core_Db_Table::getDefaultAdapter()->query("select * from question")->fetchAll();
            $question_ids = array();
            $temps = Core_Db_Table::getDefaultAdapter()->query("select question_id from nganhnghe_question  where nganhnghe_id='" . $this->form->getElement('id')->getValue() . "'")->fetchAll();
            if (is_array($temps) && count($temps) > 0) {
                foreach ($temps as $row) {
                    $question_ids[] = $row['question_id'];
                }
            }
            if (is_array($rows) && count($rows) > 0) {
                ?>
                <h3 style="text-align: center;">Chọn câu hỏi</h3>

                <?php foreach ($rows as $menu) { ?>
                    <div style="margin-left: 50px;">

                        <label>

                            <input type="checkbox" name="question_id[]" value="<?php echo $menu['id']; ?>"<?php if (in_array($menu['id'], $question_ids)) { ?> checked<?php } ?>/>
                            <?php
                            echo $menu['content'];
                            ?>
                        </label>

                    </div>    



                    <?php
                }
            }
        }
        ?>
    </div>    




</form>    

<script type="text/javascript">
    jQuery(function ($) {
        $("#sortable").sortable({
            placeholder: "ui-state-highlight"
        });
        $("#sortable").disableSelection();
        $(".sortable").sortable({
            placeholder: "ui-state-highlight"
        });
        $(".sortable").disableSelection();

        $("#form").find("input[type='text']").eq(0).focus();
    });

</script>



