<?php
$items = $this->items;



$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    $identity = $auth->getIdentity();
}


?>
<script type="text/javascript">

    function addItem() {
        window.location = "<?php echo $this->baseUrl('/admin/nganhnghe/add/'); ?>";

    }

</script>
<?php
$message = $this->message;
if ($message != "") {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span3">&nbsp;</div>
        <div class="span6" align='center' style='color: red;'>
            <?php
            echo $message;
            ?>
        </div>
        <div class="span3">&nbsp;</div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="padding-top:20px;">
    <div class="span12">
        <table width="100%" style="-moz-border-radius: 10px 10px 10px 10px;background: #D0E3F5;">
            <tr>              

                <td onclick="addItem();" onmouseover="this.style.cursor = 'pointer';" style="text-decoration: underline;color: blue;text-align: right;width: 100%;">Thêm ngành nghề</td>

            </tr>
        </table>
    </div>
</div>
<?php if (count($items) > 0) { ?>
    <form id="form1" method="post" action="<?php echo $this->url(); ?>">
        <?php
    }
    ?>
    <div class="row-fluid">

        <?php
        
        foreach ($items as $item) {


         
            ?>

            <div class="row-fluid item" id="<?php echo $item['id']; ?>">

                <div class="span10"><strong>
                        <?php echo $item['title']; ?></strong>
                </div>


                <div class="span2">
                    <a class="remove" title="Click vào đây để xóa" href="<?php echo $this->baseUrl('/admin/nganhnghe/delete/id/') . $item['id']; ?>">
                        <img class="delete question" src="<?php echo $this->baseUrl("/images/icon/delete-icon.png"); ?>"/>                                                   
                    </a>
                    <a title="Click vào đây để sửa" href="<?php echo $this->baseUrl('/admin/nganhnghe/edit/id/') . $item['id']; ?>">
                        <img style="width: 48px;height: 48px;cursor: pointer;" src="<?php echo $this->baseUrl("/images/icon/ico_edit.png"); ?>" onclick="editItem(this);"/>                                                   
                    </a>
                </div>

            </div>




            <?php
        }
        ?>

    </div>



