<script type="text/javascript">
    function save() {
        document.form1.submit();
    }
</script>
<?php
$message = $this->message;
if ($message != "") {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span3">&nbsp;</div>
        <div class="span6" align='center' style='color: red;'>
            <?php
            echo $message;
            ?>
        </div>
        <div class="span3">&nbsp;</div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='padding-bottom:20px;color: red;margin-bottom: 20px;'>
        <div class="textHeader" style="-moz-border-radius: 10px 10px 10px 10px;background-color:#f2e8e8;">
            <div style="float: left;"></div>
            <div onclick="save();" style="float: right;margin-left: 600px;text-decoration: underline;color: blue;cursor: pointer;">Lưu</div>	  
            <div style="clear: both;"></div>
        </div>

    </div>
    <div class="span3">&nbsp;</div>
</div>
<form name="form1" id="form1" action="<?php echo $this->url(); ?>" method="post">
    <div class="row-fluid">
        <div class="span12"></div>
        <?php
        $data = $this->data;
        for ($i = 0; $i < count($data); $i++) {
            ?>
            <div class="span12">
                <div class="span2" style="text-align: right;"><?php echo $data[$i]["text"]; ?>:</div>
                <div class="span10">
                    <input type="text" name="text[]" value="<?php echo $data[$i]["text"]; ?>">                        
                </div>
                <input type="hidden" name="id[]" value="<?php echo $data[$i]["id"]; ?>"/>
            </div>
            <?php
        }
        ?>
    </div>
</form>
