<link href="<?php echo $this->baseUrl(); ?>/css/question.css" rel="stylesheet" type="text/css"/>
<?php
$questions = $this->questions;
$nganhNghes = $this->nganhNghes;

if (isset($this->error) && $this->error != '') { ?>
    <div style="color: red;text-align: center;">
        <?php echo $this->error; ?>
    </div>
    <?php
}
if (!is_array($questions) || count($questions) == 0) { ?>
    <form method="POST" id="form1" onsubmit="return false;">
        <div class="row-fluid">
            <div class="span12">
                <?php
                $auth = Zend_Auth::getInstance();
                if ($auth->hasIdentity()) {
                    $identity = $auth->getIdentity();
                    $user_id = $identity['id'];
                }
                $db = Core_Db_Table::getDefaultAdapter();
                $row = $db->fetchRow("SELECT * FROM user_review WHERE user_id=" . $user_id . " ORDER BY review_date DESC LIMIT 1");
                if (is_array($row) && count($row) > 0) {
                    ?>
                    <div class="span4" style="margin-top: 20px;" onclick="viewResult();">
                        <button style="border-radius: 5px;background-color: brown;color: white;">
                            Xem kết quả lần ôn tập gần nhất
                        </button>
                    </div>
                    <?php
                } else {
                    ?>
                    <div class="span4">&nbsp;</div>
                    <?php
                }
                ?>
                <div class="span4" style="margin-top: 20px;">
                    <select id="nganh_nghe_id" name="nganh_nghe_id" style="width: 100%;">
                        <option value="0">------------------Chọn ngành nghề------------------</option>
                        <?php foreach ($nganhNghes as $nganhNghe) { ?>
                            <option value="<?php echo $nganhNghe['id']; ?>"><?php echo $nganhNghe['title']; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
                <div class="span3" style="margin-top: 20px;">
                    <select id="level" name="level" style="width: 100%;">
                        <option value="0">-----------Chọn cấp bậc-----------</option>
                        <option value="<?php echo Default_Model_Question::SO_CAP; ?>">Sơ cấp</option>
                        <option value="<?php echo Default_Model_Question::TRUNG_CAP; ?>">Trung cấp</option>
                        <option value="<?php echo Default_Model_Question::CAO_CAP; ?>">Cao cấp</option>
                    </select>
                </div>
                <div class="span1" style="margin-top: 20px;"><input type="submit" value="Bắt đầu" id="start"/></div>
            </div>
        </div>

    </form>
    <?php
}
?>
<div class="row-fluid">
    <div class="span12">&nbsp;</div>
</div>
<?php
if (is_array($questions) && count($questions) > 0) {
    $db = Core_Db_Table::getDefaultAdapter();
    $config_exam = $db->fetchRow("SELECT * FROM config_exam");
    $minute_per_question = $config_exam['phut'];
    ?>
    <div class="row-fluid" style="margin-bottom: 20px;">
        <div class="span12" style="text-align: center;margin: 0 auto;font-size: 50px;">
            <div>
                <!--<span id="h">Giờ</span> :-->
                <span id="m">Phút</span> :
                <span id="s">Giây</span>
            </div>
        </div>
        <!--<input type="hidden" id="h_val" value="1"/> <br/>-->
        <input type="hidden" id="m_val" value="<?php echo count($questions) * $minute_per_question - $this->miniutes; ?>"/> <br/>
        <input type="hidden" id="s_val" value="00"/>
    </div>


    <?php
}
?>
<form method="POST" onsubmit="return false;" id="form2">
    <?php if (is_array($questions) && count($questions) > 0) { ?>
        <div class="row-fluid" style="float: left;width: 85%;">
            <div class="span12">&nbsp;</div>
            <?php
            $i = 1;
            foreach ($questions as $question) {
                ?>
                <div>
                    <div class="span12 question" id="question_<?php echo $i; ?>">
                        <?php echo $i . '/&nbsp;&nbsp;&nbsp;' . $question['content']; ?>
                    </div>
                    <?php
                    $answers = $question['answers'];
                    foreach ($answers as $answer) {
                        ?>
                        <div class="span11 answer">
                            <label>
                                <div class='span1'>
                                    <input type="radio" name="<?php echo $question['id']; ?>" value="<?php echo $answer['id'] . '_' . $answer['sign']; ?>"/>
                                    <?php echo $answer['sign']; ?>
                                </div>
                                <div class='span11'>
                                    <?php echo $answer['content']; ?>
                                </div>
                            </label>
                        </div>
                        <?php
                    }
                    ?>
                    <input type="hidden" name="question_id[]" value="<?php echo $question['id']; ?>"/>
                    <input type="hidden" name="answer_id[]"/>
                    <input type="hidden" name="answer_sign[]"/>
                    <input type="hidden" name="dapan_sign[]" value="<?php echo $question['dapan_sign']; ?>"/>
                </div>
                <?php
                $i++;
            }
            ?>
        </div>

        <div class="row-fluid" style="width: 15%;float: left;" id="goto">

            <div class="span12" style="background-color: blanchedalmond;max-height: 200px;overflow-y: auto;">
                <?php
                $i = 1;
                if (count($questions) > 100) {
                    $num = 3;
                } else if (count($questions) > 9) {
                    $num = 2;
                } else {
                    $num = 1;
                }
                foreach ($questions as $question) {
                    ?>

                    <a class="goto" href="#question_<?php echo $i; ?>">
                        <button style="margin: 5px;">
                            <?php
                            if ($num == 3) {
                                if (strlen($i) == 1) {
                                    echo '00' . $i;
                                } else if (strlen($i) == 2) {
                                    echo '0' . $i;
                                } else {
                                    echo $i;
                                }
                            } else if ($num == 2) {
                                if (strlen($i) == 1) {
                                    echo '0' . $i;
                                } else {
                                    echo $i;
                                }
                            } else {
                                echo $i;
                            }
                            ?>
                        </button>
                    </a>                            
                    <?php
                    $i++;
                }
                ?>
            </div>
        </div>
        <?php
    }
    if (is_array($questions) && count($questions) > 0) {
        ?>
        <div class="span12" style="text-align: center;margin: 0 auto;">
            <input type="hidden" name="nganh_nghe_id_form2" value="<?php echo $this->nganhNgheId; ?>"/>
            <input type="hidden" name="level_form2" value="<?php echo $this->level; ?>"/>
            <input type="submit" value="Hoàn tất" id="finish"/>
        </div>
        <?php
    }
    ?>
</form>

<script type="text/javascript">
    function viewResult() {
        window.location = '<?php echo $this->baseUrl('/review/viewresult'); ?>';
    }
    jQuery(function ($) {
        $(window).scroll(function () {
            $("#goto").stop().animate({"marginTop": ($(window).scrollTop()) - 70 + "px", "marginLeft": ($(window).scrollLeft()) + "px"}, "slow");
        });

        $('a.goto').click(function (event) {

            // The id of the section we want to go to.
            var id = $(this).attr("href");

            // An offset to push the content down from the top.
            var offset = 60;

            // Our scroll target : the top position of the
            // section that has the id referenced by our href.
            var target = $(id).offset().top - offset;
            
            $('.span12.question').css('border','0');
            $(id).css('border','1px solid red');

            // The magic...smooth scrollin' goodness.
            $('html, body').animate({scrollTop: target}, 500);

            //prevent the page from jumping down to our section.
            event.preventDefault();
        });

        $("#start").click(function () {
            if ($("#nganh_nghe_id").val() == '0') {
                jAlert('', 'Vui lòng chọn ngành nghề');
                $("#nganh_nghe_id").focus();
                return;
            }
            if ($("#level").val() == '0') {
                jAlert('', 'Vui lòng chọn cấp bậc');
                $("#level").focus();
                return;
            }
            $("#form1").attr('onsubmit', 'return true');
            $("form1").submit();
        });
        $("#nganh_nghe_id").val('<?php echo $this->nganhNgheId; ?>');
        $("#level").val('<?php echo $this->level; ?>');

        $("#finish").click(function () {
            $("#form2").attr('onsubmit', 'return true');
            $("form2").submit();
        });

        $("input[type='radio']").click(function () {
            val = $(this).val();
            temp = val.split('_');
            answer_id = temp[0];
            answer_sign = temp[1];
            $(this).parent().parent().parent().parent().find('input[name="answer_id[]"]').eq(0).val(answer_id);
            $(this).parent().parent().parent().parent().find('input[name="answer_sign[]"]').eq(0).val(answer_sign);

            question_id = $(this).parent().parent().parent().parent().find('div.span12.question').eq(0).attr('id');
            $("a[href='#" + question_id + "']").find('button').eq(0).css('color', 'white');
            $("a[href='#" + question_id + "']").find('button').eq(0).css('background-color', 'blue');

        });
    });

//    var h = null; // Giờ
    var m = null; // Phút
    var s = null; // Giây

    var timeout = null; // Timeout

    start();
    function start()
    {
        /*BƯỚC 1: LẤY GIÁ TRỊ BAN ĐẦU*/
//        if (h === null)
//        {
//            h = parseInt(document.getElementById('h_val').value);
//            m = parseInt(document.getElementById('m_val').value);
//            s = parseInt(document.getElementById('s_val').value);
//        }
        if (m === null)
        {

            m = parseInt(document.getElementById('m_val').value);
            s = parseInt(document.getElementById('s_val').value);
        }

        /*BƯỚC 1: CHUYỂN ĐỔI DỮ LIỆU*/
        // Nếu số giây = -1 tức là đã chạy ngược hết số giây, lúc này:
        //  - giảm số phút xuống 1 đơn vị
        //  - thiết lập số giây lại 59
        if (s === -1) {
            m -= 1;
            s = 59;
        }

        // Nếu số phút = -1 tức là đã chạy ngược hết số phút, lúc này:
        //  - giảm số giờ xuống 1 đơn vị
        //  - thiết lập số phút lại 59
//        if (m === -1){
//            h -= 1;
//            m = 59;
//        }

        // Nếu số giờ = -1 tức là đã hết giờ, lúc này:
        //  - Dừng chương trình
//        if (h == -1){
//            clearTimeout(timeout);
//            alert('Hết giờ');
//            return false;
//        }
        if (m == -1) {
            clearTimeout(timeout);
            jAlert('', 'Hết giờ.');
            setTimeout(function () {
                $("#finish").click();
            }, 2000);
            return false;
        }

        /*BƯỚC 1: HIỂN THỊ ĐỒNG HỒ*/
        document.getElementById('m').innerText = m.toString();
        document.getElementById('s').innerText = s.toString();

        /*BƯỚC 1: GIẢM PHÚT XUỐNG 1 GIÂY VÀ GỌI LẠI SAU 1 GIÂY */
        timeout = setTimeout(function () {
            s--;
            start();
        }, 1000);
    }
</script>