<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    jQuery(function ($) {
        CKEDITOR.replace('editor1', {
            language: 'en',
            filebrowserUploadUrl: '/upload.php'
        });
    });

    function save() {
        document.form1.submit();
    }

</script>
<?php
$message = $this->message;
if ($message != "") {
    ?>
    <div style="color: red;text-align: center;width: 100%;">
        <h3><?php echo $this->message; ?></h3>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 20px;margin-bottom: 20px;">
    <div class="span12" style="text-align: right;">
        <input onclick="save();" type="button" value="Lưu" class="button" />
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <form name="form1" enctype="multipart/form-data" id="form1" action="<?php echo $this->baseUrl('/admin/homecontent/save'); ?>" method="post">
            <div class="row-fluid" style="margin-top: 10px;">

                <div class="span12">
                    <textarea rows="" cols="" name="content" id="editor1"><?php echo $this->content; ?></textarea>
                </div>
            </div>
        </form>
    </div>
</div>

