<link href="<?php echo $this->baseUrl(); ?>/css/question.css" rel="stylesheet" type="text/css"/>
<?php 
if ($this->success != '') { ?>
    <div style="color: red;text-align: center;width: 100%;padding-top: 20px;">
        <h3><?php echo $this->success; ?></h3>
    </div>
    <?php
} else {
    if (isset($this->message) && $this->message != '') {
        ?>
        <div style="color: red;text-align: center;width: 100%;padding-top: 20px;">
            <h3><?php echo $this->message; ?></h3>
        </div>
        <?php
    }
}

$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    $identity = $auth->getIdentity();
    $user_id = $identity['id'];
}
$db = Core_Db_Table::getDefaultAdapter();
$row = $db->fetchRow("SELECT * FROM user_exam WHERE user_id=" . $user_id . " ORDER BY exam_date DESC LIMIT 1");
if (is_array($row) && count($row) > 0 && (!isset($this->showFormNganhNgheCapBac) || $this->showFormNganhNgheCapBac == FALSE)) {
    ?>
    <div class="row-fluid">
        <div class="span12">
            <div class="span4" style="margin-top: 20px;" onclick="viewResult();">
                <button style="border-radius: 5px;background-color: brown;color: white;">
                    Xem kết quả lần thi gần nhất
                </button>
            </div>
        </div>
    </div>
    <?php
}
if (isset($this->showFormNganhNgheCapBac) && $this->showFormNganhNgheCapBac == true) { 
    echo $this->render('thi/partial/form_nganhnghe_capbac.phtml');
}
?>
<div class="row-fluid">
    <div class="span12">&nbsp;</div>
</div>
<?php 
if (is_array($this->questions) && count($this->questions) > 0) {
    echo $this->render('thi/partial/form_question.phtml');
}
?>


<script type="text/javascript">
    function viewResult() {
        window.location = '<?php echo $this->baseUrl('/thi/viewresult'); ?>';
    }    
</script>