<?php 
$menu_items=$GLOBALS['menu_items'];
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    $hrefThi = $this->baseUrl('/thi');
    $hrefReview = $this->baseUrl('/review');
    $idReview=$idThi='';
} else {
    $hrefThi = $hrefReview = 'javascript:void(0)';
    $idThi=' id="thi"';
    $idReview=' id="review"';
    
}
?>
<div class="span12" style="padding: 20px;">
    <ul id="topnav">
        <li<?php if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'index') echo ' class="active"'; ?>><a href="<?php echo $this->baseUrl(); ?>/"><?php echo $menu_items[0]; ?></a></li>
        <li<?php echo $idThi; if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'thi') echo ' class="active"'; ?>><a href="<?php echo $hrefThi; ?>"><?php echo $menu_items[1]; ?></a></li>                        
        <li<?php echo $idReview; if (Zend_Controller_Front::getInstance()->getRequest()->getControllerName() == 'review') echo ' class="active"'; ?>><a href="<?php echo $hrefReview; ?>"><?php echo $menu_items[2]; ?></a></li>                        
        <li><a href="<?php echo $this->baseUrl(); ?>/index/guide"><?php echo $menu_items[3]; ?></a></li>                        
    </ul>
</div>
