<script type="text/javascript">



    function save() {
        document.form1.submit();
    }

</script>
<?php
$item = $this->item;
$message = $this->message;
if ($message != "") {
    ?>
    <div style="color: red;text-align: center;width: 100%;">
        <h3><?php echo $this->message; ?></h3>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 20px;margin-bottom: 20px;">
    <div class="span12" style="text-align: right;">
        <input onclick="save();" type="button" value="Lưu" class="button" />
    </div>
</div>
<div class="row-fluid">
    <div class="span5"></div>
    <div class="span7">
        <form name="form1" enctype="multipart/form-data" id="form1" action="<?php echo $this->baseUrl('/admin/guide/save'); ?>" method="post">
            <div class="row-fluid">
                <div class="span12">
                    <?php
                    if ($item != "") {
                        echo '<a href="' . $this->baseUrl() . '/admin/guide/download">download file hướng dẫn sử dụng hiện tại</a>';
                    }
                    ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <p>                                            
                        <input type="file" name="hinhnen"/>
                    </p>                
                </div>
            </div>


        </form>
    </div>

</div>

