<script type="text/javascript">



    function save() {
        document.form1.submit();
    }

</script>
<?php
$item = $this->item;
$message = $this->message;
if ($message != "") {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span3">&nbsp;</div>
        <div class="span6" align='center' style='color: red;'>
            <?php
            echo $message;
            ?>
        </div>
        <div class="span3">&nbsp;</div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='padding-bottom:20px;color: red;margin-bottom: 20px;'>
        <div class="textHeader" style="-moz-border-radius: 10px 10px 10px 10px;background-color:#f2e8e8;">
            <div style="float: left;"></div>
            <div onclick="save();" style="float: right;margin-left: 600px;text-decoration: underline;color: blue;cursor: pointer;">Lưu</div>	  
            <div style="clear: both;"></div>
        </div>

    </div>
    <div class="span3">&nbsp;</div>
</div>
<div class="row-fluid">
    <div class="span5">&nbsp;</div>
    <div class="span7">
        <form name="form1" enctype="multipart/form-data" id="form1" action="<?php echo $this->baseUrl('/admin/guide/save'); ?>" method="post">
            <div class="row-fluid">
                <div class="span12">
                    <?php
                    if ($item != "") {
                        echo '<a href="' . $this->baseUrl() . '/admin/guide/download">download file hướng dẫn sử dụng hiện tại</a>';
                    }
                    ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <p>                                            
                        <input type="file" name="hinhnen"/>
                    </p>                
                </div>
            </div>


        </form>
    </div>

</div>

