<style>
    fieldset{
        border: 1px solid black;
        margin-bottom: 50px;
    }
</style>
<script type="text/javascript">
    function save() {
        document.form1.submit();
    }
</script>
<?php
$message = $this->message;
if ($message != "") {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span3">&nbsp;</div>
        <div class="span6" align='center' style='color: red;'>
            <?php
            echo $message;
            ?>
        </div>
        <div class="span3">&nbsp;</div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span3">&nbsp;</div>
    <div class="span6" align='center' style='padding-bottom:20px;color: red;margin-bottom: 20px;'>
        <div class="textHeader" style="-moz-border-radius: 10px 10px 10px 10px;background-color:#f2e8e8;">
            <div style="float: left;"></div>
            <div onclick="save();" style="float: right;margin-left: 600px;text-decoration: underline;color: blue;cursor: pointer;">Lưu</div>	  
            <div style="clear: both;"></div>
        </div>

    </div>
    <div class="span3">&nbsp;</div>
</div>
<form name="form1" enctype="multipart/form-data" id="form1" action="<?php echo $this->url(); ?>" method="post">
    <fieldset style="padding: 20px;">
        <?php echo $this->render('headerfooter/partial/header.phtml');?>
    </fieldset>

    <fieldset style="padding: 20px;">
        <?php echo $this->render('headerfooter/partial/footer.phtml');?> 
    </fieldset>
    
</form>
