<script type="text/javascript">
    function save() {
        document.form1.submit();
    }
</script>
<?php
$message = $this->message;
if ($message != "") {
    ?>
    <div style="color: red;text-align: center;width: 100%;">
        <h3><?php echo $this->message; ?></h3>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 20px;margin-bottom: 20px;">
    <div class="span12" style="text-align: right;">
        <input onclick="save();" type="button" value="Lưu" class="button" />
    </div>
</div>
<form name="form1" enctype="multipart/form-data" id="form1" action="<?php echo $this->url(); ?>" method="post">
    <fieldset style="padding: 20px;">
        <?php echo $this->render('headerfooter/partial/header.phtml');?>
    </fieldset>

    <fieldset style="padding: 20px;">
        <?php echo $this->render('headerfooter/partial/footer.phtml');?> 
    </fieldset>
    
</form>
