<?php if (isset($this->message) && $this->message != '') { ?>
    <div style="color: red;text-align: center;width: 100%;">
        <h3><?php echo $this->message; ?></h3>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 20px;margin-bottom: 20px;">
    <div class="span12" style="text-align: right;">
        <input onclick="save();" type="button" value="Lưu" class="button" />
    </div>
</div>

<form name="form" enctype="multipart/form-data" id="form" method="post"> 
    <fieldset>
        <?php echo $this->render('exam/partial/examtime.phtml');?>
    </fieldset>

    <fieldset>
        <?php echo $this->render('exam/partial/config.phtml');?> 
    </fieldset>
    
</form>
<script type="text/javascript">
    function save() {
        document.form.submit();
    }
</script>